apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: fcg
  labels:
    app: notifications-api
data:
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Queues__UserCreated: "fcg.user-created"
  RabbitMQ__Queues__PaymentProcessed: "fcg.payment-processed"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__MassTransit: "Information"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"
  Smtp__Host: "smtp.gmail.com"
  Smtp__Port: "587"
  Smtp__SenderName: "FIAP Cloud Games"
