apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
  namespace: fcg
  labels:
    app: notifications-api
data:
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Queues__UserCreated: "fcg.user-created"
  RabbitMQ__Queues__PaymentProcessed: "fcg.payment-processed"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__MassTransit: "Information"
  # Host do PostgreSQL dentro do cluster
  ConnectionStrings__DefaultConnection__Host: "postgres"
  ConnectionStrings__DefaultConnection__Database: "fcg_notifications"
