apiVersion: v1
kind: Secret
metadata:
  name: notifications-api-secrets
  namespace: fcg
  labels:
    app: notifications-api
type: Opaque
stringData:
  RabbitMQ__Username: "fcg_user"
  RabbitMQ__Password: "fcg_password"
  ConnectionStrings__DefaultConnection: "Host=fiapcloudgames;Database=fcg_notifications;Username=fcg_user;Password=fcg_password"
  Smtp__Username: "seuemail@gmail.com"
  Smtp__Password: "sua-app-password-aqui"
  Smtp__SenderEmail: "seuemail@gmail.com"
